//
// Created by konghaomin on 23-12-12.
//

#ifndef NEW_YEAR_OPENCL_CONFIG_H
#define NEW_YEAR_OPENCL_CONFIG_H

#define ORIGIN_CANVAS_WIDTH 1920
#define ORIGIN_CANVAS_HEIGHT 1080

#define ORIGIN_FRAME_RATE 60

#define SCALE 1.0f
#define FRAME_RATE_SCALE 1.0f

#define CANVAS_WIDTH (ORIGIN_CANVAS_WIDTH * SCALE)
#define CANVAS_HEIGHT (ORIGIN_CANVAS_HEIGHT * SCALE)

#define CANVAS_CENTER_X (CANVAS_WIDTH / 2)
#define CANVAS_CENTER_Y (CANVAS_HEIGHT / 2)

#define FRAME_RATE (ORIGIN_FRAME_RATE * FRAME_RATE_SCALE)

// Program IO

#define SEP_LINE_LENGTH 80

#endif //NEW_YEAR_OPENCL_CONFIG_H
